/* tslint:disable */

/**
 * This file was automatically generated by "Swaxios".
 * It should not be modified by hand.
 */

export interface ObjectIdentity {
  issuer?: string;
  issuerAssignedId?: string;
  signInType?: string;
  _odata_type?: string;
}
