/* tslint:disable */

/**
 * This file was automatically generated by "Swaxios".
 * It should not be modified by hand.
 */

import {ObjectIdentity} from './ObjectIdentity';

export interface OrganizationUser {
  id?: string;
  displayName?: string;
  givenName?: string;
  surname?: string;
  userPrincipalName?: string;
  orgId?: string;
  orgRole?: string;
  signInNames?: Array<string>;
  identities?: Array<ObjectIdentity>;
}
