/* tslint:disable */

/**
 * This file was automatically generated by "Swaxios".
 * It should not be modified by hand.
 */

import {AxiosInstance, AxiosRequestConfig} from 'axios';
import {AppRole} from '../../../interfaces/';

export class AppRolesService {
  private readonly apiClient: AxiosInstance;

  constructor(apiClient: AxiosInstance) {
    this.apiClient = apiClient;
  }

  getByResourceId = async (resourceId: string): Promise<Array<AppRole>> => {
    const config: AxiosRequestConfig = {
      method: 'get',
      url: `/v1.0/servicePrincipals/${resourceId}/appRoles`,
    };
    const response = await this.apiClient.request<Array<AppRole>>(config);
    return response.data;
  };
}
