/* tslint:disable */

/**
 * This file was automatically generated by "Swaxios".
 * It should not be modified by hand.
 */

import {AxiosInstance, AxiosRequestConfig} from 'axios';
import {AppRoleAssignment} from '../../../interfaces/';

export class AppRoleAssignedToService {
  private readonly apiClient: AxiosInstance;

  constructor(apiClient: AxiosInstance) {
    this.apiClient = apiClient;
  }

  getByServicePrincipalId = async (
    servicePrincipalId: string,
    params?: {
      resourceId?: string;
    }
  ): Promise<Array<AppRoleAssignment>> => {
    const config: AxiosRequestConfig = {
      method: 'get',
      params,
      url: `/v1.0/servicePrincipals/${servicePrincipalId}/appRoleAssignedTo`,
    };
    const response = await this.apiClient.request<Array<AppRoleAssignment>>(
      config
    );
    return response.data;
  };

  postByServicePrincipalId = async (
    servicePrincipalId: string,
    body?: AppRoleAssignment,
    params?: {
      resourceId?: string;
    }
  ): Promise<AppRoleAssignment> => {
    const config: AxiosRequestConfig = {
      data: {
        ...body,
      },
      method: 'post',
      params,
      url: `/v1.0/servicePrincipals/${servicePrincipalId}/appRoleAssignedTo`,
    };
    const response = await this.apiClient.request<AppRoleAssignment>(config);
    return response.data;
  };
}
