/* tslint:disable */

/**
 * This file was automatically generated by "Swaxios".
 * It should not be modified by hand.
 */

import {AxiosInstance, AxiosRequestConfig} from 'axios';
import {AppRoleAssignment} from '../../../interfaces/';

export class AppRoleAssignedToService {
  private readonly apiClient: AxiosInstance;

  constructor(apiClient: AxiosInstance) {
    this.apiClient = apiClient;
  }

  getByResourceId = async (
    resourceId: string
  ): Promise<Array<AppRoleAssignment>> => {
    const config: AxiosRequestConfig = {
      method: 'get',
      url: `/v1.0/servicePrincipals/${resourceId}/appRoleAssignedTo`,
    };
    const response = await this.apiClient.request<Array<AppRoleAssignment>>(
      config
    );
    return response.data;
  };

  postByResourceId = async (
    resourceId: string,
    body?: AppRoleAssignment
  ): Promise<AppRoleAssignment> => {
    const config: AxiosRequestConfig = {
      data: {
        ...body,
      },
      method: 'post',
      url: `/v1.0/servicePrincipals/${resourceId}/appRoleAssignedTo`,
    };
    const response = await this.apiClient.request<AppRoleAssignment>(config);
    return response.data;
  };
}
