/* tslint:disable */

/**
 * This file was automatically generated by "Swaxios".
 * It should not be modified by hand.
 */

export * from './AppRoleAssignedToService';
export * from './AppRolesService';
