/* tslint:disable */

/**
 * This file was automatically generated by "Swaxios".
 * It should not be modified by hand.
 */

import {AxiosInstance, AxiosRequestConfig} from 'axios';
import {OrganizationUser} from '../../interfaces/';

export class UsersService {
  private readonly apiClient: AxiosInstance;

  constructor(apiClient: AxiosInstance) {
    this.apiClient = apiClient;
  }

  getAll = async (): Promise<Array<OrganizationUser>> => {
    const config: AxiosRequestConfig = {
      method: 'get',
      url: '/v1.0/Users',
    };
    const response = await this.apiClient.request<Array<OrganizationUser>>(
      config
    );
    return response.data;
  };

  getByUserId = async (userId: string): Promise<OrganizationUser> => {
    const config: AxiosRequestConfig = {
      method: 'get',
      url: `/v1.0/Users/${userId}`,
    };
    const response = await this.apiClient.request<OrganizationUser>(config);
    return response.data;
  };
}
